### PR TITLE
added issue_template.md

### PR DESCRIPTION
**Pull request by Shatakshi0805**
part of #20

### CODE REVIEW

**Review by rodrigo-brito — APPROVED** [review]
Hi @Shatakshi0805, it looks great!
Thank you!

**Comment by Shatakshi0805** [comment]
hi, i just wanted to know like how can i claim this PR for hacktoberfest? Its my first time participating in Hacktoberfest so could you please tell the same?

**Comment by rodrigo-brito** [comment]
@Shatakshi0805  it is an automatic process. You have to sign up on the site: https://hacktoberfest.digitalocean.com/
Then the hacktober site will fetch your PRs with Github API.
The rules are:
```
A valid pull request is one that is accepted by the maintainer of the project you submit it to.

A pull request is considered approved once it has an overall approving review from maintainers, or has been merged by maintainers, or has been given the 'hacktoberfest-accepted' label. 
The pull request must contain commits you made yourself.
```
Infos: https://hacktoberfest.digitalocean.com/faq

**Comment by Shatakshi0805** [comment]
okay, thanks for informing.

**Pull request merged**
